/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base.datos.swing;
import ThingMagic.Readers.MercuryReader;
import java.io.IOException;
import java.net.UnknownHostException;
import java.sql.*;
import java.util.Date;
import java.util.concurrent.TimeUnit;
/**
 *
 * @author luisj
 */
public class GUI extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pre;
    //String epc = "";
    //String nombre = "";
    //String matricula = "";
    //String tipopersonal = "";
    //String archivo ="";
    int change = -1;
    String epc = "";
    String FirstName = "";
    String LastName1 = "";
    String LastName2 = "";
    String ImageLocation = "";
    int Autorization = 0;
    Date date = new Date();
    long time = date.getTime();
    Timestamp ts = new Timestamp(time);
    private MercuryReader m4reader;
    


    /**
     * Creates new form swing
     */
    public GUI() {
        initComponents();
        initDBComponents();
        initRFIDComponents();
    }
    private void initRFIDComponents()
    {
        try 
        {
            m4reader = new MercuryReader(this);
        }catch (UnknownHostException ex) 
        {
            show("Error: " + ex.toString());
        }catch (IOException ex) 
        {
            show("Error: " + ex.toString());
        }
    }
        private void initDBComponents(){
        try
        { 
            String driverName = "com.mysql.jdbc.Driver";
            Class.forName(driverName);
	   //  Código usado para un servidor local
            //String serverName = "sql10.freemysqlhosting.net";
            //String mydatabase = "sql10282032";
            //String url = "jdbc:mysql://" + serverName + "/" + mydatabase;
            //String username = "sql10282032";
            //String password = "xIaVIMkM2q";
            String serverName = "localhost";
            String mydatabase = "rfidsecurity";
            String url = "jdbc:mysql://" + serverName + "/" + mydatabase;
            String username = "root";
            String password = "";
            conn = DriverManager.getConnection(url, username, password);
	    // Usar el siguiente código en caso de querer eliminar la tabla PersonasTEC 
            // pre = conn.prepareStatement("DROP TABLE IF EXISTS PersonasTEC");
            // pre.executeUpdate();
            //System.out.println("Se pudo establecer conexión con la base de datos.");
            show("Conexión a la base de datos exitosa.");
            
        }
        catch (Exception e)
        {
            //System.out.println("No se pudo establecer conexión con la base de datos.");
            show("No se pudo establecer conexión con la base de datos.");
        }
    }
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFirstName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        GuardRegister = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JButtonEnviarSQL = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLastName1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLastName2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jEPCguard = new javax.swing.JTextField();
        ReadEPC = new javax.swing.JButton();
        CredentialEdition = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldEPC2 = new javax.swing.JTextField();
        jButtonLeeSQL = new javax.swing.JButton();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jTextLastName1 = new javax.swing.JTextField();
        jTextLastName2 = new javax.swing.JTextField();
        removeCredentials = new javax.swing.JButton();
        LeerEPC2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextLastEntrance = new javax.swing.JTextField();
        JTextLastExit = new javax.swing.JTextField();
        jTextInside = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextAuthorization = new javax.swing.JTextField();
        eliminateGuard = new javax.swing.JButton();
        giveCredentials = new javax.swing.JButton();
        AntennaAdministration = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextPower = new javax.swing.JTextField();
        changePower = new javax.swing.JButton();
        getPower = new javax.swing.JButton();
        DisplayData = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextFieldEPC4 = new javax.swing.JTextField();
        jButtonLeeSQL3 = new javax.swing.JButton();
        jTextFieldNombre4 = new javax.swing.JTextField();
        jTextLastName7 = new javax.swing.JTextField();
        jTextLastName8 = new javax.swing.JTextField();
        removeCredentials3 = new javax.swing.JButton();
        startStopLecture = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextLastEntrance3 = new javax.swing.JTextField();
        JTextLastExit3 = new javax.swing.JTextField();
        jTextInside3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jTextAuthorization3 = new javax.swing.JTextField();
        eliminateGuard3 = new javax.swing.JButton();
        giveCredentials3 = new javax.swing.JButton();
        jTextAreaShow = new javax.swing.JTextArea();
        jButtonExit = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jLabel10.setText("jLabel10");

        jFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstNameActionPerformed(evt);
            }
        });
        jFirstName.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("ACTUALIZACIÓN DE INFORMACIÓN A BASE DE DATOS MYSQL");

        jLabel2.setText("Ingresar datos en los siguientes campos");

        jLabel6.setText("Primer Nombre:");

        JButtonEnviarSQL.setText("Registrar Guardia");
        JButtonEnviarSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEnviarSQLActionPerformed(evt);
            }
        });

        jLabel16.setText("Apellido Paterno:");

        jLabel17.setText("Apellido Materno:");

        jLastName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastName2ActionPerformed(evt);
            }
        });

        jLabel5.setText("EPC:");

        ReadEPC.setLabel("Leer EPC");
        ReadEPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadEPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GuardRegisterLayout = new javax.swing.GroupLayout(GuardRegister);
        GuardRegister.setLayout(GuardRegisterLayout);
        GuardRegisterLayout.setHorizontalGroup(
            GuardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardRegisterLayout.createSequentialGroup()
                .addGroup(GuardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GuardRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLastName1))
                    .addGroup(GuardRegisterLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLastName2))
                    .addGroup(GuardRegisterLayout.createSequentialGroup()
                        .addGroup(GuardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addGroup(GuardRegisterLayout.createSequentialGroup()
                                .addGap(319, 319, 319)
                                .addComponent(JButtonEnviarSQL))
                            .addGroup(GuardRegisterLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEPCguard, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ReadEPC)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GuardRegisterLayout.setVerticalGroup(
            GuardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GuardRegisterLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(GuardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jEPCguard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReadEPC))
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addGroup(GuardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GuardRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1989, Short.MAX_VALUE)
                .addComponent(JButtonEnviarSQL)
                .addContainerGap())
        );

        ReadEPC.getAccessibleContext().setAccessibleName("LeerEPC");

        jTabbedPane3.addTab("Registro nuevo Guardia", GuardRegister);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("LECTURA DE BASE DE DATOS");

        jLabel9.setText("Ingrese el código EPC(24 caracteres hex)");

        jLabel11.setText("EPC");

        jLabel12.setText("RESULTADOS:");

        jLabel13.setText("Nombre");

        jLabel14.setText("Apellido Paterno");

        jLabel15.setText("Apellido Materno");

        jTextFieldEPC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEPC2ActionPerformed(evt);
            }
        });

        jButtonLeeSQL.setText("Deplegar Guardia");
        jButtonLeeSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeeSQLActionPerformed(evt);
            }
        });

        jTextLastName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastName1ActionPerformed(evt);
            }
        });

        jTextLastName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastName2ActionPerformed(evt);
            }
        });

        removeCredentials.setText("Remover Credenciales");
        removeCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCredentialsActionPerformed(evt);
            }
        });

        LeerEPC2.setLabel("Leer EPC");
        LeerEPC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerEPC2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Última Entrada");

        jLabel8.setText("Última Salida");

        jLabel18.setText("Ubicación");

        jTextInside.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextInsideActionPerformed(evt);
            }
        });

        jLabel19.setText("Autorización");

        jTextAuthorization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAuthorizationActionPerformed(evt);
            }
        });

        eliminateGuard.setText("Eliminar Guardia");

        giveCredentials.setText("Otorgar Credenciales");
        giveCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveCredentialsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLastName1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addComponent(jTextLastName2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLastEntrance))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(14, 14, 14)
                        .addComponent(JTextLastExit))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextInside))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextAuthorization))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEPC2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LeerEPC2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(removeCredentials)
                                .addGap(33, 33, 33)
                                .addComponent(eliminateGuard, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(giveCredentials, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jButtonLeeSQL, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldEPC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeerEPC2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLeeSQL)
                .addGap(5, 5, 5)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextLastEntrance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JTextLastExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jTextInside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jTextAuthorization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeCredentials)
                    .addComponent(eliminateGuard)
                    .addComponent(giveCredentials)))
        );

        removeCredentials.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout CredentialEditionLayout = new javax.swing.GroupLayout(CredentialEdition);
        CredentialEdition.setLayout(CredentialEditionLayout);
        CredentialEditionLayout.setHorizontalGroup(
            CredentialEditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CredentialEditionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );
        CredentialEditionLayout.setVerticalGroup(
            CredentialEditionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CredentialEditionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Edición Credenciales", CredentialEdition);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Administración de Antena");

        jLabel23.setText("Seleccionar Intensidad:");

        changePower.setText("AjustarPoder");
        changePower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePowerActionPerformed(evt);
            }
        });

        getPower.setText("Leer Valor Actual");
        getPower.setActionCommand("Leer Valor Actual");
        getPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPowerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 593, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPower)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(changePower, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(getPower, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePower)
                    .addComponent(getPower))
                .addContainerGap())
        );

        javax.swing.GroupLayout AntennaAdministrationLayout = new javax.swing.GroupLayout(AntennaAdministration);
        AntennaAdministration.setLayout(AntennaAdministrationLayout);
        AntennaAdministrationLayout.setHorizontalGroup(
            AntennaAdministrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AntennaAdministrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );
        AntennaAdministrationLayout.setVerticalGroup(
            AntennaAdministrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AntennaAdministrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Administración de Antena", AntennaAdministration);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Despliegue de datos");

        jLabel44.setText("EPC");

        jLabel45.setText("RESULTADOS:");

        jLabel46.setText("Nombre");

        jLabel47.setText("Apellido Paterno");

        jLabel48.setText("Apellido Materno");

        jTextFieldEPC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEPC4ActionPerformed(evt);
            }
        });

        jButtonLeeSQL3.setText("Deplegar Guardia");
        jButtonLeeSQL3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeeSQL3ActionPerformed(evt);
            }
        });

        jTextLastName7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastName7ActionPerformed(evt);
            }
        });

        jTextLastName8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastName8ActionPerformed(evt);
            }
        });

        removeCredentials3.setText("Remover Credenciales");
        removeCredentials3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCredentials3ActionPerformed(evt);
            }
        });

        startStopLecture.setText("Empezar/Detener Lectura");
        startStopLecture.setActionCommand("Iniciar Lectura");
        startStopLecture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopLectureActionPerformed(evt);
            }
        });

        jLabel49.setText("Última Entrada");

        jLabel50.setText("Última Salida");

        jLabel51.setText("Ubicación");

        jTextInside3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextInside3ActionPerformed(evt);
            }
        });

        jLabel52.setText("Autorización");

        jTextAuthorization3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAuthorization3ActionPerformed(evt);
            }
        });

        eliminateGuard3.setText("Eliminar Guardia");

        giveCredentials3.setText("Otorgar Credenciales");
        giveCredentials3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveCredentials3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLastName7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(2, 2, 2)
                        .addComponent(jTextLastName8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLastEntrance3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(14, 14, 14)
                        .addComponent(JTextLastExit3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextInside3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextAuthorization3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addGap(171, 171, 171)
                                .addComponent(jButtonLeeSQL3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEPC4, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(removeCredentials3)
                                .addGap(33, 33, 33)
                                .addComponent(eliminateGuard3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(giveCredentials3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(startStopLecture))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startStopLecture)
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jTextFieldEPC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonLeeSQL3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jTextFieldNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jTextLastName7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLastName8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(jTextLastEntrance3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(JTextLastExit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addComponent(jTextInside3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(jTextAuthorization3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeCredentials3)
                    .addComponent(eliminateGuard3)
                    .addComponent(giveCredentials3)))
        );

        javax.swing.GroupLayout DisplayDataLayout = new javax.swing.GroupLayout(DisplayData);
        DisplayData.setLayout(DisplayDataLayout);
        DisplayDataLayout.setHorizontalGroup(
            DisplayDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );
        DisplayDataLayout.setVerticalGroup(
            DisplayDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Despliegue de Datos", DisplayData);

        jTextAreaShow.setColumns(20);
        jTextAreaShow.setRows(5);

        jButtonExit.setText("Salir de la Aplicación");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextAreaShow, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButtonExit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addGap(18, 18, 18)
                .addComponent(jTextAreaShow, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExit)
                .addGap(61, 61, 61))
        );

        jTabbedPane3.getAccessibleContext().setAccessibleName("Panel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
                if (conn != null)
        {
            try
            {
                conn.close();
            }
            catch (Exception e) { /* ignore close errors */}
        }
        System.exit(0);

    }//GEN-LAST:event_jButtonExitActionPerformed
    public void show(String response) { 
        jTextAreaShow.append(response + "\n");
    }

    private void jFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstNameActionPerformed

    private void giveCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveCredentialsActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE employee SET Autorization = ? where EPC = ?;";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "1");
            ps.setString(2, jTextFieldEPC2.getText());
            ps.executeUpdate();
            ps.close();
            show("Credenciales modificadas");

        }
        catch (Exception e)
        {
            show("Error. No se pudieron modificar las credenciales.");
        }
    }//GEN-LAST:event_giveCredentialsActionPerformed

    private void jTextAuthorizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAuthorizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAuthorizationActionPerformed

    private void jTextInsideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextInsideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextInsideActionPerformed

    private void LeerEPC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerEPC2ActionPerformed
        String alfa = "SELECT read_count, protocol_id, antenna_id, id FROM tag_id WHERE protocol_id='GEN2' set time_out=1000;";
        m4reader.doCommand(alfa);
        String beta = jTextAreaShow.getText();

        int index = 0;
        for(int i = 0; i<beta.length()-1; i++){
            if(beta.charAt(i)=='x')
            {
                index = i;
            }
        }
        System.out.println(index);
        String gamma = beta.substring(index+1, beta.length()-6);
        jTextFieldEPC2.setText(gamma);
    }//GEN-LAST:event_LeerEPC2ActionPerformed

    private void removeCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCredentialsActionPerformed
        try{
            String sql = "UPDATE employee SET Autorization = ? where EPC = ?;";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, "0");
            ps.setString(2, jTextFieldEPC2.getText());
            ps.executeUpdate();
            ps.close();
            show("Credenciales modificadas");

        }
        catch (Exception e)
        {
            show("Error. No se pudieron modificar las credenciales.");
        }
    }//GEN-LAST:event_removeCredentialsActionPerformed

    private void jTextLastName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastName2ActionPerformed

    private void jTextLastName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastName1ActionPerformed

    private void jButtonLeeSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeeSQLActionPerformed
        try
        {

            String sql = "select ID, FirstName, LastName1, LastName2, Autorization, LastEntrance, LastExit, inside from employee where EPC = "+ "'"+jTextFieldEPC2.getText()+"'"+";";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next())
            {
                String FirstNameVal = rs.getString("FirstName");
                String LastName1Val = rs.getString("LastName1");
                String LastName2Val = rs.getString("LastName2");
                String AuthorizationVal = rs.getString("Autorization");
                String LastEntranceVal = rs.getString("LastEntrance");
                String LastExitVal = rs.getString("LastExit");
                String insideVal = rs.getString("inside");

                jTextFieldNombre1.setText(FirstNameVal);
                jTextLastName1.setText(LastName1Val);
                jTextLastName2.setText(LastName2Val);
                jTextLastEntrance.setText(LastEntranceVal);
                JTextLastExit.setText(LastExitVal);
                if(Integer.parseInt(insideVal)==1)
                {
                    jTextInside.setText("Dentro");
                }
                else{
                    jTextInside.setText("Fuera");
                }
                jTextAuthorization.setText(AuthorizationVal);

                show("Lectura de base datos exitosa.");

            }
            rs.close ();
            ps.close ();
        }
        catch (Exception e)
        {
            show("Error. No se pudo ejecutar la función SELECT.");
        }
    }//GEN-LAST:event_jButtonLeeSQLActionPerformed

    private void jTextFieldEPC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEPC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEPC2ActionPerformed

    private void ReadEPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadEPCActionPerformed
        // TODO add your handling code here:

        //jTextAreaShow.setText("");
        String alfa = "SELECT read_count, protocol_id, antenna_id, id FROM tag_id WHERE protocol_id='GEN2' set time_out=1000;";
        m4reader.doCommand(alfa);
        String beta = jTextAreaShow.getText();

        int index = 0;
        for(int i = 0; i<beta.length()-1; i++){
            if(beta.charAt(i)=='x')
            {
                index = i;
            }
        }
        System.out.println(index);
        String gamma = beta.substring(index+1, beta.length()-6);
        jEPCguard.setText(gamma);
    }//GEN-LAST:event_ReadEPCActionPerformed

    private void jLastName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastName2ActionPerformed

    private void JButtonEnviarSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEnviarSQLActionPerformed
        // TODO add your handling code here:
        try
        {
            epc = jEPCguard.getText();
            FirstName = jFirstName.getText();
            LastName1 = jLastName1.getText();
            LastName2 = jLastName2.getText();
            ImageLocation = "C:\\Users\\luisj\\Desktop\\IMGS\\Laverga.jpg";
            int inside = 0;
            Date date = new Date();
            long time = date.getTime();
            Timestamp ts = new Timestamp(time);
            pre = conn.prepareStatement("INSERT INTO employee (EPC, FirstName"
                + ", LastName1, LastName2, ImageLocation, Autorization,"
                + "LastEntrance, LastExit, inside) VALUES(?,?,?,?,?,?,?,?,?);");

            pre.setString(1, epc);
            pre.setString(2, FirstName);
            pre.setString(3, LastName1);
            pre.setString(4, LastName2);
            pre.setString(5,ImageLocation);
            pre.setString(6, ""+Autorization);
            pre.setString(7,""+ts);
            pre.setString(8,""+ts);
            pre.setString(9, ""+inside);

            pre.executeUpdate();
            pre.close();
            show("Actualización de base datos exitosa.");
        }
        catch (Exception e)
        {
            show("Error al enviar la información a la base de datos.");
        }
    }//GEN-LAST:event_JButtonEnviarSQLActionPerformed

    private void jTextInside3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextInside3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextInside3ActionPerformed

    private void jTextAuthorization3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAuthorization3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAuthorization3ActionPerformed

    private void giveCredentials3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveCredentials3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giveCredentials3ActionPerformed

    private void removeCredentials3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCredentials3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCredentials3ActionPerformed

    private void jTextLastName8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastName8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastName8ActionPerformed

    private void jTextLastName7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastName7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastName7ActionPerformed

    private void jButtonLeeSQL3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeeSQL3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLeeSQL3ActionPerformed

    private void startStopLectureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopLectureActionPerformed
        //String alfa = "SELECT read_count, protocol_id, antenna_id, id FROM tag_id WHERE protocol_id='GEN2' set time_out=1000;";
        //m4reader.doCommand(alfa);
        String controlEPC = "";
        
        //String gamma = beta.substring(index+1, beta.length()-6);
        //jTextFieldEPC4.setText(gamma);
        
        try
        {

            String sql = "EPC, select ID, FirstName, LastName1, LastName2, Autorization, LastEntrance, LastExit, inside from employee where EPC = "+ "'"+jTextFieldEPC2.getText()+"'"+";";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while (rs.next())
            {
                controlEPC = rs.getString("EPC");
                String FirstNameVal = rs.getString("FirstName");
                String LastName1Val = rs.getString("LastName1");
                String LastName2Val = rs.getString("LastName2");
                String AuthorizationVal = rs.getString("Autorization");
                String LastEntranceVal = rs.getString("LastEntrance");
                String LastExitVal = rs.getString("LastExit");
                String insideVal = rs.getString("inside");

                jTextFieldNombre1.setText(FirstNameVal);
                jTextLastName1.setText(LastName1Val);
                jTextLastName2.setText(LastName2Val);
                jTextLastEntrance.setText(LastEntranceVal);
                JTextLastExit.setText(LastExitVal);
                if(Integer.parseInt(insideVal)==1)
                {
                    jTextInside.setText("Dentro");
                }
                else{
                    jTextInside.setText("Fuera");
                }
                jTextAuthorization.setText(AuthorizationVal);

                show("Lectura de base datos exitosa.");

            }
            rs.close ();
            ps.close ();
        }
        catch (Exception e)
        {
            show("Error. No se pudo ejecutar la función SELECT.");
        }
        try
        {
            String sql = "SELECT EPC, count(*) as NUM FROM  employee where EPC = '"+ jTextFieldEPC4.getText()+"';";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            controlEPC = rs.getString("count");
        }
        catch(Exception e)
        {
            
        }
        if(Integer.parseInt(controlEPC)==1){
            String command = "UPDATE io SET data = 0x00 WHERE type = 0 and mask = 0x08;";
            m4reader.doCommand(command);
        }
        else
        {
            String command = "UPDATE io SET data = 0x00 WHERE type = 0 and mask = 0x04;";
            m4reader.doCommand(command);
        }
    }//GEN-LAST:event_startStopLectureActionPerformed

    private void jTextFieldEPC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEPC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEPC4ActionPerformed

    private void changePowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePowerActionPerformed
        // TODO add your handling code here:
        String comando = "UPDATE saved_settings SET tx_power= '" +jTextPower.getText()+"';";
        m4reader.doCommand(comando);
    }//GEN-LAST:event_changePowerActionPerformed

    private void getPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPowerActionPerformed
        // TODO add your handling code here:
        m4reader.doCommand("SELECT tx_power FROM Saved_settings;");
    }//GEN-LAST:event_getPowerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AntennaAdministration;
    private javax.swing.JPanel CredentialEdition;
    private javax.swing.JPanel DisplayData;
    private javax.swing.JPanel GuardRegister;
    private javax.swing.JButton JButtonEnviarSQL;
    private javax.swing.JTextField JTextLastExit;
    private javax.swing.JTextField JTextLastExit2;
    private javax.swing.JTextField JTextLastExit3;
    private javax.swing.JButton LeerEPC2;
    private javax.swing.JButton LeerEPC4;
    private javax.swing.JButton ReadEPC;
    private javax.swing.JButton changePower;
    private javax.swing.JButton eliminateGuard;
    private javax.swing.JButton eliminateGuard2;
    private javax.swing.JButton eliminateGuard3;
    private javax.swing.JButton getPower;
    private javax.swing.JButton giveCredentials;
    private javax.swing.JButton giveCredentials2;
    private javax.swing.JButton giveCredentials3;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLeeSQL;
    private javax.swing.JButton jButtonLeeSQL2;
    private javax.swing.JButton jButtonLeeSQL3;
    private javax.swing.JTextField jEPCguard;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLastName1;
    private javax.swing.JTextField jLastName2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextAreaShow;
    private javax.swing.JTextField jTextAuthorization;
    private javax.swing.JTextField jTextAuthorization2;
    private javax.swing.JTextField jTextAuthorization3;
    private javax.swing.JTextField jTextFieldEPC2;
    private javax.swing.JTextField jTextFieldEPC3;
    private javax.swing.JTextField jTextFieldEPC4;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNombre3;
    private javax.swing.JTextField jTextFieldNombre4;
    private javax.swing.JTextField jTextInside;
    private javax.swing.JTextField jTextInside2;
    private javax.swing.JTextField jTextInside3;
    private javax.swing.JTextField jTextLastEntrance;
    private javax.swing.JTextField jTextLastEntrance2;
    private javax.swing.JTextField jTextLastEntrance3;
    private javax.swing.JTextField jTextLastName1;
    private javax.swing.JTextField jTextLastName2;
    private javax.swing.JTextField jTextLastName5;
    private javax.swing.JTextField jTextLastName6;
    private javax.swing.JTextField jTextLastName7;
    private javax.swing.JTextField jTextLastName8;
    private javax.swing.JTextField jTextPower;
    private javax.swing.JButton removeCredentials;
    private javax.swing.JButton removeCredentials2;
    private javax.swing.JButton removeCredentials3;
    private javax.swing.JButton startStopLecture;
    // End of variables declaration//GEN-END:variables
}
